export default {
  CHANGE_PROJECT: 'CHANGE_CURRENT_PROJECT',
  PROJECT_LOADED: 'PROJECT_LOADED',

  SAVE_PROJECT: 'SAVE_PROJECT',

  /* AppLogin */
  LOGIN: 'LOGIN',

  /* AppDashboard */
  LOGOUT: 'LOGOUT',
  NEW_PROJECT: 'NEW_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',

  /* AppSideBar */
  CLICK_APP_MENU: 'CLICK_APP_MENU',
  TOGGLE_APP_SIDEBAR: 'TOGGLE_APP_SIDEBAR',

  /* AppToolBar */
  TOGGLE_CONTEXT_SIDEBAR: 'TOGGLE_CONTEXT_SIDEBAR',
  CHANGE_PATH: 'CHANGE_PATH',

  /* AnalysisBoard */
  CHANGE_DAG: 'CHANGE_DAG',
  CLOSE_NODE_EDITOR: 'CLOSE_NODE_EDITOR',
  OPEN_NODE_EDITOR: 'OPEN_NODE_EDITOR',
  SELECT_NODE: 'SELECT_NODE',
  SUBMIT_NODE_CONFIG: 'SUBMIT_NODE_CONFIG',

  /* Variables */
  SELECT_VARIABLE: 'SELECT_VARIABLE',
  CHANGE_VARIABLES: 'CHANGE_VARIABLES',

  /* Execution Engines*/
  CHANGE_EXECUTION_ENGINES: 'CHANGE_EXECUTION_ENGINES',

  /* Scheduler */
  CHANGE_TRIGGERS: 'CHANGE_TRIGGERS',

	/* Notification */
	DISPLAY_MESSAGE: 'DISPLAY_MESSAGE',
	DISPOSE_MESSAGE: 'DISPOSE_MESSAGE',
}
